__description__ = 'Sismic Interactive Statechart Model Interpreter and Checker'
__version__ = '0.22.8'
__url__ = 'https://github.com/AlexandreDecan/sismic/'
__author__ = 'Alexandre Decan'
__email__ = 'alexandre.decan@lexpage.net'
__licence__ = 'LGPL3'